### ISSUE TITLE
Support for Eclipse Photon

### ISSUE THREAD

**Issue by FulekiDani** [IncQueryLabs/rcptt-remote-configuration#1]

**Comment by ujhelyiz** [comment]
Stupid question: what is unsupported wrt Eclipse Photon? As far as I can see in the code (https://github.com/IncQueryLabs/rcptt-remote-configuration/blob/master/com.incquerylabs.rcptt.remote.setup/RemoteRCPTTConfiguration.setup#L194), between Neon and 2020-06 all versions have corresponding configuration added. And if I recall correctly, I have even further versions created locally, but as I was not finished testing them, I did not upload them.

**Comment by ujhelyiz** [comment]
Fixed with #2
